repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # TODO Update
    hooks:
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0 # TODO Update
    hooks:
      - id: terraform_docs
        args:
          - --args=--lockfile=false
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - TODO
      - id: terraform_validate
