name: renovate

on:
  schedule:
    # Every day at 3:20 am
    - cron: "20 3 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
